language: haskell

matrix:
  allow_failures:
    - env: GHCVER=head
#    - env: GHCVER=7.0.4 THVER=-2.6.0.0 QCVER=-2.5.*
#    - env: GHCVER=7.2.2 THVER=-2.6.0.0 QCVER=-2.5.*

env:
 - GHCVER=7.6.3
 - GHCVER=head
# - GHCVER=7.0.4 THVER=-2.6.0.0 QCVER=-2.5.*
# - GHCVER=7.2.2 THVER=-2.6.0.0 QCVER=-2.5.*
# - GHCVER=7.4.2
# - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - travis_retry cabal-1.18 update

install:
 - travis_retry cabal-1.18 install --only-dependencies
 - make prepare
 - cabal-1.18 install --enable-tests

script:
 - echo "All done."
